# core/verbs.py — verb phrases + regex builder

import re

VERB_PHRASES = [
    # perception
    "detect","detects","detecting","detection","ability to detect","perform detection",
    "identify","identifies","identifying","identification","ability to identify","perform identification",
    "recognize","recognizes","recognizing","recognition","ability to recognize","demonstrate recognition",
    "differentiate","differentiates","differentiating","differentiation","ability to differentiate",
    "observe","observes","observing","observation","ability to observe","perform observation",
    "notice","notices","noticing","ability to notice",
    "hear","hears","hearing","ability to hear",
    "listen","listens","listening","ability to listen","demonstrate listening",
    "feel","feels","feeling","ability to feel",
    "watch","watches","watching","ability to watch",
    "sense","senses","sensing","ability to sense",
    "distinguish","distinguishes","distinguishing","ability to distinguish",
    "select","selects","selecting","selection","ability to select","perform selection",
    # set
    "prepare","prepares","preparing","preparation","ability to prepare","perform preparation",
    "position","positions","positioning","position","ability to position",
    "show","shows","showing","ability to show",
    "demonstrate","demonstrates","demonstrating","demonstration","ability to demonstrate",
    "arrange","arranges","arranging","arrangement","ability to arrange",
    "assemble","assembles","assembling","assembly","ability to assemble","carry out assembly",
    "organize","organizes","organizing","organization","ability to organize",
    "align","aligns","aligning","alignment","ability to align",
    "begin","begins","beginning","ability to begin",
    "start","starts","starting","ability to start",
    "react","reacts","reacting","reaction","ability to react",
    "display","displays","displaying","display","ability to display",
    "initiate","initiates","initiating","initiation","ability to initiate",
    # guided response
    "imitate","imitates","imitating","imitation","ability to imitate",
    "copy","copies","copying","copy","ability to copy",
    "follow","follows","following","ability to follow",
    "reproduce","reproduces","reproducing","reproduction","ability to reproduce",
    "replicate","replicates","replicating","replication","ability to replicate",
    "attempt","attempts","attempting","attempt","ability to attempt",
    "try","tries","trying","ability to try",
    "respond","responds","responding","response","ability to respond",
    "practice","practices","practicing","practice","ability to practice",
    "repeat","repeats","repeating","repetition","ability to repeat",
    "perform","performs","performing","performance","ability to perform",
    "sketch","sketches","sketching","sketch","ability to sketch",
    # mechanism/complex overt
    "operate","operates","operating","operation","ability to operate",
    "manipulate","manipulates","manipulating","manipulation","ability to manipulate",
    "use","uses","using","usage","ability to use",
    "execute","executes","executing","execution","ability to execute",
    "measure","measures","measuring","measurement","ability to measure",
    "calibrate","calibrates","calibrating","calibration","ability to calibrate","perform calibration",
    "adjust","adjusts","adjusting","adjustment","ability to adjust",
    "control","controls","controlling","control","ability to control",
    "dismantle","dismantles","dismantling","dismantlement","ability to dismantle",
    "carry out","carries out","carrying out","carried out","ability to carry out",
    "handle","handles","handling","ability to handle",
    "solder","solders","soldering","solder","ability to solder",
    "mount","mounts","mounting","mount","ability to mount",
    "tune","tunes","tuning","ability to tune",
    # complex overt/precision
    "fabricate","fabricates","fabricating","fabrication","ability to fabricate",
    "construct","constructs","constructing","construction","ability to construct",
    "build","builds","building","build","ability to build",
    "machine","machines","machining","machining","ability to machine",
    "implement","implements","implementing","implementation","ability to implement",
    "illustrate","illustrates","illustrating","illustration","ability to illustrate",
    "complete","completes","completing","completion","ability to complete",
    "refine","refines","refining","refinement","ability to refine",
    "maneuver","maneuvers","maneuvering","maneuver","ability to maneuver",
    "present","presents","presenting","presentation","ability to present",
    # adaptation/origination
    "adapt","adapts","adapting","adaptation","ability to adapt",
    "modify","modifies","modifying","modification","ability to modify",
    "revise","revises","revising","revision","ability to revise",
    "troubleshoot","troubleshoots","troubleshooting","troubleshooting","ability to troubleshoot",
    "alter","alters","altering","alteration","ability to alter",
    "customize","customizes","customizing","customization","ability to customize",
    "reorganize","reorganizes","reorganizing","reorganization","ability to reorganize",
    "solve","solves","solving","solution","ability to solve",
    "change","changes","changing","change","ability to change",
    "update","updates","updating","update","ability to update",
    "correct","corrects","correcting","correction","ability to correct",
    "improve","improves","improving","improvement","ability to improve",
    "reconfigure","reconfigures","reconfiguring","reconfiguration","ability to reconfigure",
    "extend","extends","extending","extension","ability to extend",
    "vary","varies","varying","variation","ability to vary",
    # creation/origination
    "design","designs","designing","design","ability to design",
    "create","creates","creating","creation","ability to create",
    "develop","develops","developing","development","ability to develop",
    "compose","composes","composing","composition","ability to compose",
    "invent","invents","inventing","invention","ability to invent",
    "generate","generates","generating","generation","ability to generate",
    "formulate","formulates","formulating","formulation","ability to formulate",
    "innovate","innovates","innovating","innovation","ability to innovate",
    "plan","plans","planning","plan","ability to plan",
    "integrate","integrates","integrating","integration","ability to integrate",
    "propose","proposes","proposing","proposal","ability to propose",
    "engineer","engineers","engineering","engineering","ability to engineer",
]

def build_verb_regex():
    phrases = sorted({p.strip().lower() for p in VERB_PHRASES if p.strip()}, key=len, reverse=True)
    if not phrases:
        return re.compile(r"(?!x)x")
    pat = "|".join(re.escape(p) for p in phrases)
    return re.compile(rf"(?<!\w)(?:{pat})(?!\w)", re.IGNORECASE)
